# Infrared Remote Controller
target = B1IrRC
src = main.c stm8_interrupt_vector.c stm8s_it.c \
	ext_uart.c ext_ir_decoder.c ext_ir_nec.c ext_ir_sony.c ext_unique_id.c\
	stm8s_clk.c stm8s_gpio.c stm8s_exti.c stm8s_tim3.c stm8s_uart2.c

!INCLUDE <../stm8.mk>